/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_UltimateAlprSdk_WRAP_H_
#define SWIG_UltimateAlprSdk_WRAP_H_

namespace Swig {
  class Director;
}


struct SwigDirector_UltAlprSdkParallelDeliveryCallback : public ultimateAlprSdk::UltAlprSdkParallelDeliveryCallback, public Swig::Director {

public:
    SwigDirector_UltAlprSdkParallelDeliveryCallback(VALUE self);
    virtual ~SwigDirector_UltAlprSdkParallelDeliveryCallback();
    virtual void onNewResult(ultimateAlprSdk::UltAlprSdkResult const *result) const;
};


#endif
