/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.ultimateAlpr.Sdk;

public interface ultimateAlprSdkConstants {
  public final static int ULTALPR_SDK_VERSION_MAJOR = 3;
  public final static int ULTALPR_SDK_VERSION_MINOR = 4;
  public final static int ULTALPR_SDK_VERSION_MICRO = 0;
}
